version: "18.14.2"

services:
  node3:
    image: kardinalanna/blockchain
    container_name: node2
    command: "index.js 2"
    ports:
        - "3002:3002"
    stdin_open: true
    tty: true


  node2:
    image: kardinalanna/blockchain
    container_name: node1
    command: "index.js 1"
    ports:
        - "3001:3001"
    stdin_open: true
    tty: true

  node1:
    image: kardinalanna/blockchain
    container_name: node0
    command: "index.js 0"
    ports:
        - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - node2
      - node3