version: "18.14.2"

services:
  node3:
    image: kardinalanna/blockchain
    container_name: node2
    command: "index.js 2"
    ports:
        - "3002:3002"
    environment:
      ADRESS: http://node2:3002
      OTHERS: http://node0:3000,http://node1:3001
      PORT: 3002
    stdin_open: true
    tty: true


  node2:
    image: kardinalanna/blockchain
    container_name: node1
    command: "index.js 1"
    ports:
        - "3001:3001"
    environment:
      ADRESS: http://node1:3001
      OTHERS: http://node0:3000,http://node2:3002
      PORT: 3001
    stdin_open: true
    tty: true

  node1:
    image: kardinalanna/blockchain
    container_name: node0
    command: "index.js 0"
    ports:
        - "3000:3000"
    environment:
      ADRESS: http://node0:3000
      OTHERS: http://node1:3001,http://node2:3002
      PORT: 3000
    stdin_open: true
    tty: true
    depends_on:
      - node2
      - node3