name: Tests-Miniblockchain

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  testing_app:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Test with jest
        run: npm test

        
